In [1]:
import pandas as pd

In [2]:
import sys
import traceback
import warnings


import warnings

def custom_warning_format(message, category, *args, **kwargs):
    print(f"{category.__name__}: {message}")  # Affiche le type de warning + message seulement

warnings.showwarning = custom_warning_format

def custom_excepthook(exc_type, exc_value, exc_traceback):
    if exc_traceback:
        last_tb = traceback.extract_tb(exc_traceback)[-1]  # Dernière ligne de l'erreur
        print(f"Erreur : {exc_type.__name__}: {exc_value} (ligne {last_tb.lineno})")
    else:
        print(f"Erreur : {exc_type.__name__}: {exc_value}")

#sys.excepthook = custom_excepthook

# exercice 1
## CustomerNAme et Order anonymiser

In [3]:


custo=pd.Series(['John Smith','John Smith','Tom Smith','Jane Doe','Alex William'])
order=pd.Series(['Laptop','Router','Router','TV','Cable'])

data=pd.DataFrame({'CustomerName':custo,'Order':order})
data


# ano = rang dans la liste de valeur unique des champs str trié par ordre lexico
def ano_data(df):
    unique_values_cust =df['CustomerName'].unique()
    unique_values_cust.sort()
    print(unique_values_cust)
    my_dict={}
    for index, element in enumerate(unique_values_cust):
        my_dict[element] = index
    print(my_dict)
    print("++++++++++++++++")
    for idx, values in my_dict.items():
        print(idx,values)
        df.replace(idx, values, inplace=True)
    print("---------------")
    print(df)
    print("***************")
    unique_values_order =df['Order'].unique()
    unique_values_order.sort()
    print(unique_values_order)
    my_dict={}
    for index, element in enumerate(unique_values_order):
        my_dict[element] = index
    print(my_dict)
    print("++++++++++++++++")
    for idx, values in my_dict.items():
        print(idx,values)
        df.replace(idx, values, inplace=True)
    return df

print(data)
ano_data(data)

   CustomerName   Order
0    John Smith  Laptop
1    John Smith  Router
2     Tom Smith  Router
3      Jane Doe      TV
4  Alex William   Cable
['Alex William' 'Jane Doe' 'John Smith' 'Tom Smith']
{'Alex William': 0, 'Jane Doe': 1, 'John Smith': 2, 'Tom Smith': 3}
++++++++++++++++
Alex William 0
Jane Doe 1
John Smith 2
Tom Smith 3
---------------
   CustomerName   Order
0             2  Laptop
1             2  Router
2             3  Router
3             1      TV
4             0   Cable
***************
['Cable' 'Laptop' 'Router' 'TV']
{'Cable': 0, 'Laptop': 1, 'Router': 2, 'TV': 3}
++++++++++++++++
Cable 0
Laptop 1
Router 2
TV 3

   CustomerName  Order
0             2      1
1             2      2
2             3      2
3             1      3
4             0      0

In [4]:
import pandas as pd
# Create a DataFrame
data = {'A': [1, 2, 3],
        'B': [4, 5, 6]}
df = pd.DataFrame(data)
# Dictionary to update values
update_dict = {'A': [10, 20, 30]}
# Update DataFrame using the dictionary
df.update(pd.DataFrame(update_dict))
print(df)

    A  B
0  10  4
1  20  5
2  30  6

In [5]:
# Create a DataFrame
data = {'A': [1, 2, 3],
        'B': [4, 5, 6]}
df = pd.DataFrame(data)

# Dictionary to update values for specific rows
update_dict_rows = {1: {'A': 50, 'B': 60}}

# Update DataFrame using the dictionary
for idx, values in update_dict_rows.items():
    print(idx,values)
    df.loc[idx] = values

print(df)

1 {'A': 50, 'B': 60}
    A   B
0   1   4
1  50  60
2   3   6

In [6]:
my_list = ['Alex William' ,'Jane Doe', 'John Smith', 'Tom Smith']
my_dict = {}

for index, element in enumerate(my_list):
    my_dict[element] = index

print(my_dict)

{'Alex William': 0, 'Jane Doe': 1, 'John Smith': 2, 'Tom Smith': 3}

# version ok

In [7]:
# exercice 1

def init_data():
    custo=pd.Series(['John Smith','John Smith','Tom Smith','Jane Doe','Alex William'])
    order=pd.Series(['Laptop','Router','Router','TV','Cable'])
    data=pd.DataFrame({'CustomerName':custo,'Order':order})
    print( "table de code")
    print(custo.drop_duplicates().sort_values())
    new_custo=custo.drop_duplicates().sort_values()
    print(order.drop_duplicates().sort_values())
    print( "-----------------")
    X=custo.drop_duplicates().sort_values()
    print(X.index)
    print( "-----------------")
    print (pd.Series(new_custo.index.values, index=new_custo ))
    print( "-----------------")
    s1 = pd.Series(dict((v,k) for k,v in new_custo.items()))
    print(s1)
    print( "////////////////////////////")
    return data


# ano = rang dans la liste de valeur unique des champs str trié par ordre lexico
def ano_data(df):
    unique_values_cust =df['CustomerName'].unique()
    unique_values_cust.sort()
    my_dict={}
    for index, element in enumerate(unique_values_cust):
        my_dict[element] = index
    for idx, values in my_dict.items():
        df.replace(idx, values, inplace=True)
    unique_values_order =df['Order'].unique()
    unique_values_order.sort()
    my_dict={}
    for index, element in enumerate(unique_values_order):
        my_dict[element] = index
    for idx, values in my_dict.items():
        df.replace(idx, values, inplace=True)
    return df

#++++++++++++++++
#Alex William 0
#Jane Doe 1
#John Smith 2
#Tom Smith 3
#--------------

# ano = rang dans la liste de valeur unique des champs str trié par ordre lexico
def ano_data2(df):
    new_custo=df['CustomerName'].drop_duplicates().sort_values(ascending=True,ignore_index=True) 
    new_custo_code=pd.Series(new_custo.index.values, index=new_custo )
    new_custo_code = new_custo_code[::-1]
    for idx, values in new_custo_code.items():
        df.replace(idx, values, inplace=True) 
    new_order=df['Order'].drop_duplicates().sort_values(ascending=True,ignore_index=True)
    new_order_code=pd.Series(new_order.index.values, index=new_order )
    for idx, values in new_order_code.items():
        df.replace(idx, values, inplace=True)
    return df


my_data=init_data()
print(my_data)
print( "RESULTAT-----------------------")
print(ano_data2(my_data))
print( "*==============================*")
my_data=init_data()
ano_data(my_data)

table de code
4    Alex William
3        Jane Doe
0      John Smith
2       Tom Smith
dtype: object
4     Cable
0    Laptop
1    Router
3        TV
dtype: object
-----------------
Int64Index([4, 3, 0, 2], dtype='int64')
-----------------
Alex William    4
Jane Doe        3
John Smith      0
Tom Smith       2
dtype: int64
-----------------
Alex William    4
Jane Doe        3
John Smith      0
Tom Smith       2
dtype: int64
////////////////////////////
   CustomerName   Order
0    John Smith  Laptop
1    John Smith  Router
2     Tom Smith  Router
3      Jane Doe      TV
4  Alex William   Cable
RESULTAT-----------------------
   CustomerName  Order
0             2      1
1             2      2
2             3      2
3             1      3
4             0      0
*==============================*
table de code
4    Alex William
3        Jane Doe
0      John Smith
2       Tom Smith
dtype: object
4     Cable
0    Laptop
1    Router
3        TV
dtype: object
-----------------
Int64Index([4, 3, 0, 2], dtype='int64')
-----------------
Alex William    4
Jane Doe        3
John Smith      0
Tom Smith       2
dtype: int64
-----------------
Alex William    4
Jane Doe        3
John Smith      0
Tom Smith       2
dtype: int64
////////////////////////////

   CustomerName  Order
0             2      1
1             2      2
2             3      2
3             1      3
4             0      0

# EXERCICE 2
## encadrement des outliers

In [8]:
# EXERCICE 2

def init_data():
    C1 = pd.Series([-21.57,1.24,-0.84,32.35,0.82,-3.11,0.46,-18.68,0.04,30.87])
    C2 = pd.Series([2.49,  2.27,0.25 ,-2.33,-2.91,-3.61,0.58,-2.59,-3.99,1.54])
    C3 = pd.Series([1.14,4.76,14.23,-2.65,-3.53,-0.03,17.5,-0.21,2.96,2.31])
    data = pd.DataFrame({'C1': C1, 'C2': C2, 'C3': C3})
    return data
init_data()

      C1    C2     C3
0 -21.57  2.49   1.14
1   1.24  2.27   4.76
2  -0.84  0.25  14.23
3  32.35 -2.33  -2.65
4   0.82 -2.91  -3.53
5  -3.11 -3.61  -0.03
6   0.46  0.58  17.50
7 -18.68 -2.59  -0.21
8   0.04 -3.99   2.96
9  30.87  1.54   2.31

Valeur manquantes :

Df. dropna()
Df.dropna ( subset= ..)

Df.fillna("0")
Df.dropna ( subset= ..).fillna("0")

Df[col].fillna(df[col].mean() ]

df.isnull().mean().sort_values(ascending=False)
---------------------------------------------------
Q3 + 1.5 * IQR > outlier > Q1 -1.5 * IQR

Q1,Q3= df.ma_var.quantile([0.25,0.75])
IQR= Q3-Q1

# condition
df2=df.loc[(df['Discount'] >= 1000) & (df['Discount'] <= 2000)]

# Replace values of columns by using DataFrame.loc[] property.
df.loc[df['Fee'] > 22000, 'Fee'] = 15000

In [9]:
def handle_col(df,coll):
    newdf = df.copy()
    print(coll)
    Q1,Q3= df.loc[:,coll].quantile([0.25,0.75])
    IQR= Q3-Q1
    lim_inf=Q1-1.5*IQR
    lim_sup=Q3+1.5*IQR
    print(Q1,Q3,IQR,lim_inf,lim_sup)
    # premier sup a lim_inf
    min_no=df.loc[(df.loc[:,coll] >= lim_inf)].min()
    min_no_Col=min_no[coll]
    print("min",min_no)
    print(min_no[coll])
    # premier inf a lim_sup
    max_no=df.loc[(df.loc[:,coll] <= lim_sup)].max()
    print("/////",max_no)
    max_no_Col=max_no[coll]
    print("max",max_no)
    print("---",max_no[coll])
    df.loc[df.loc[:,coll] < lim_inf, coll]=min_no_Col
    df.loc[df.loc[:,coll] > lim_sup, coll]=max_no_Col
    print(df)
def handle_outliers(df):
    handle_col(df,'C1')
    handle_col(df,'C2')
    handle_col(df,'C3')
    
my_data=init_data()
print(my_data)
handle_outliers(my_data)

      C1    C2     C3
0 -21.57  2.49   1.14
1   1.24  2.27   4.76
2  -0.84  0.25  14.23
3  32.35 -2.33  -2.65
4   0.82 -2.91  -3.53
5  -3.11 -3.61  -0.03
6   0.46  0.58  17.50
7 -18.68 -2.59  -0.21
8   0.04 -3.99   2.96
9  30.87  1.54   2.31
C1
-2.5425 1.135 3.6775 -8.05875 6.65125
min C1   -3.11
C2   -3.99
C3   -3.53
dtype: float64
-3.11
///// C1     1.24
C2     2.49
C3    17.50
dtype: float64
max C1     1.24
C2     2.49
C3    17.50
dtype: float64
--- 1.24
     C1    C2     C3
0 -3.11  2.49   1.14
1  1.24  2.27   4.76
2 -0.84  0.25  14.23
3  1.24 -2.33  -2.65
4  0.82 -2.91  -3.53
5 -3.11 -3.61  -0.03
6  0.46  0.58  17.50
7 -3.11 -2.59  -0.21
8  0.04 -3.99   2.96
9  1.24  1.54   2.31
C2
-2.83 1.3 4.13 -9.025 7.495
min C1   -3.11
C2   -3.99
C3   -3.53
dtype: float64
-3.99
///// C1     1.24
C2     2.49
C3    17.50
dtype: float64
max C1     1.24
C2     2.49
C3    17.50
dtype: float64
--- 2.49
     C1    C2     C3
0 -3.11  2.49   1.14
1  1.24  2.27   4.76
2 -0.84  0.25  14.23
3  1.24 -2.33  -2.65
4  0.82 -2.91  -3.53
5 -3.11 -3.61  -0.03
6  0.46  0.58  17.50
7 -3.11 -2.59  -0.21
8  0.04 -3.99   2.96
9  1.24  1.54   2.31
C3
-0.16499999999999998 4.31 4.475 -6.8774999999999995 11.022499999999999
min C1   -3.11
C2   -3.99
C3   -3.53
dtype: float64
-3.53
///// C1    1.24
C2    2.49
C3    4.76
dtype: float64
max C1    1.24
C2    2.49
C3    4.76
dtype: float64
--- 4.76
     C1    C2    C3
0 -3.11  2.49  1.14
1  1.24  2.27  4.76
2 -0.84  0.25  4.76
3  1.24 -2.33 -2.65
4  0.82 -2.91 -3.53
5 -3.11 -3.61 -0.03
6  0.46  0.58  4.76
7 -3.11 -2.59 -0.21
8  0.04 -3.99  2.96
9  1.24  1.54  2.31

# version OK

In [10]:
def handle_col(df,coll):
    Q1,Q3= df.loc[:,coll].quantile([0.25,0.75])
    IQR= Q3-Q1
    lim_inf=Q1-1.5*IQR
    lim_sup=Q3+1.5*IQR
    # premier sup a lim_inf
    min_no=df.loc[(df.loc[:,coll] >= lim_inf)].min()
    min_no_Col=min_no[coll]
    # premier inf a lim_sup
    max_no=df.loc[(df.loc[:,coll] <= lim_sup)].max()
    max_no_Col=max_no[coll]
    df.loc[df.loc[:,coll] < lim_inf, coll]=min_no_Col
    df.loc[df.loc[:,coll] > lim_sup, coll]=max_no_Col
def handle_outliers(df):
    handle_col(df,'C1')
    handle_col(df,'C2')
    handle_col(df,'C3')
    return df

my_data=init_data()
print(my_data)
handle_outliers(my_data)

      C1    C2     C3
0 -21.57  2.49   1.14
1   1.24  2.27   4.76
2  -0.84  0.25  14.23
3  32.35 -2.33  -2.65
4   0.82 -2.91  -3.53
5  -3.11 -3.61  -0.03
6   0.46  0.58  17.50
7 -18.68 -2.59  -0.21
8   0.04 -3.99   2.96
9  30.87  1.54   2.31

     C1    C2    C3
0 -3.11  2.49  1.14
1  1.24  2.27  4.76
2 -0.84  0.25  4.76
3  1.24 -2.33 -2.65
4  0.82 -2.91 -3.53
5 -3.11 -3.61 -0.03
6  0.46  0.58  4.76
7 -3.11 -2.59 -0.21
8  0.04 -3.99  2.96
9  1.24  1.54  2.31

# Exercice 3

In [11]:
def init_data3():
    BrandName_S = pd.Series([ 'Lowell','Lowell','Purewash','Wilson','Purewash','Purewash','Lowell','Wilson','Lowell','Wilson','Purewash','Wilson'])
    Score_S = pd.Series([0.743,0.741,0.784,float('nan'),0.968,0.840,float('nan'),float('nan'),0.451,0.739,0.539,0.485])
    scores_df = pd.DataFrame({'BrandName': BrandName_S, 'Score': Score_S })
    BrandName_S2 = pd.Series([ 'Lowell','Purewash','Wilson'])
    Price_S2 = pd.Series([135.75,122.61,113.67])
    prices_df = pd.DataFrame({'BrandName': BrandName_S2, 'Price': Price_S2 })
    return scores_df,prices_df
init_data3()

(   BrandName  Score
 0     Lowell  0.743
 1     Lowell  0.741
 2   Purewash  0.784
 3     Wilson    NaN
 4   Purewash  0.968
 5   Purewash  0.840
 6     Lowell    NaN
 7     Wilson    NaN
 8     Lowell  0.451
 9     Wilson  0.739
 10  Purewash  0.539
 11    Wilson  0.485,
   BrandName   Price
 0    Lowell  135.75
 1  Purewash  122.61
 2    Wilson  113.67)

# version OK 
## score, price et Brandname machine wash

In [12]:
def rank_washing_machines(scores_df, prices_df):
    # Your code goes here
    new_df=(scores_df.groupby('BrandName')['Score'].mean()).reset_index()
    new_df=new_df.rename(columns={'Score':'AvgScore'})
    inner_merged_df = new_df.merge(
      prices_df,
      left_on = ["BrandName"],
      right_on = ["BrandName"],
      how = "inner"
    )
    inner_merged_df['prix_aj']=inner_merged_df['Price']/inner_merged_df['AvgScore']
    inner_merged_df=inner_merged_df.sort_values('prix_aj', ascending = True,ignore_index=True)
    inner_merged_df=inner_merged_df.drop(['prix_aj'], axis=1)
    columns_titles = ["BrandName","Price","AvgScore"]
    inner_merged_df=inner_merged_df.reindex(columns=columns_titles)
    return inner_merged_df

In [13]:
scores_df1, prices_df1=init_data3()
rank_washing_machines(scores_df1, prices_df1)

  BrandName   Price  AvgScore
0  Purewash  122.61   0.78275
1    Wilson  113.67   0.61200
2    Lowell  135.75   0.64500

# TEST : SENTENCE

# VErsion OK

In [14]:
def tokenize_sentence(sentence):
    punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    for ele in sentence:
        if ele in punc:
            sentence = sentence.replace(ele, "")
    new_sentence1=sentence.split()
    new_sentence2_set=set(new_sentence1)
    new_sentence2 = [e for e in new_sentence2_set]
    new_sentence2.sort() 
    answer=[new_sentence2.index(e) for e in new_sentence1]
    return answer

In [15]:
sentence = 'they know her , jill . but she does not know them .'
sentence_bis = 'we came , we saw , we conquered .' 
sentence_ter = 'square : a shape that is a rectangle'

print(sentence, '\n')   # Example input
print(tokenize_sentence(sentence))

they know her , jill . but she does not know them .

[8, 4, 2, 3, 0, 6, 1, 5, 4, 7]

In [16]:
sentence_bis = 'we came , we saw , we conquered .' 
print(tokenize_sentence(sentence_bis))

[3, 0, 3, 2, 3, 1]

In [17]:
sentence_ter = 'square : a shape that is a rectangle'
print(tokenize_sentence(sentence_ter))

[4, 0, 3, 5, 1, 0, 2]

# array normalize

# version OK

In [18]:
import numpy as np
def standardize_data(arr):
    # Your code goes here
    centre_gravite = np.mean(arr, axis=1)
    row,_l=arr.shape
    #print(row,col)
    cg_r=centre_gravite.reshape(row,1)
    Y=arr-cg_r
    std_r=np.std(arr, 1).reshape(row,1)
    Z=Y/std_r
    # si ecart type =0 => mettre valeur np.inf a la place de nan
    Z[np.isnan(Z)] = np.inf
    return Z

In [19]:
# WARNING
arr = np.array([
    [1.2, -0.3, 1.3],
    [1.2, 2., 0.3]
]).astype(np.float64)

arr_bis = np.array([
  [10.3, 0.5, -1.2],
  [1., 1., 1.],
  [-5.4, 10., 1.]
]).astype(np.float64)

arr_ter = np.array([
  [7.2, 1.1, -14., 10.3],
  [2.2, 0., 0.4, 9.9]
]).astype(np.float64)


print(arr, '\n')   # Example input
print(standardize_data(arr))
print(standardize_data(arr_bis))
print(standardize_data(arr_ter))

[[ 1.2 -0.3  1.3]
 [ 1.2  2.   0.3]]

[[ 0.63768253 -1.41201131  0.77432878]
 [ 0.04800154  1.2000384  -1.24803994]]
RuntimeWarning: invalid value encountered in divide
[[ 1.40089141 -0.53273335 -0.86815806]
 [        inf         inf         inf]
 [-1.15036775  1.28756757 -0.13719982]]
[[ 0.64691084 -0.00534637 -1.6199503   0.97838582]
 [-0.23134491 -0.78157063 -0.68152959  1.69444513]]

In [20]:
arr = np.array([
    [1.2, -0.3, 1.3],
    [1.2, 2., 0.3]
]).astype(np.float64)
centre_gravite = np.mean(arr, axis=1)
print(centre_gravite)
print(centre_gravite.reshape(2,1))
cg_r=centre_gravite.reshape(2,1)
print('----------------')
#mat_centre= np.hstack([centre_gravite] *2).reshape (2,2)
#print(mat_centre)
Y=arr-cg_r
print(Y)
ecarts_types = np.std(arr)
print(ecarts_types)
std_r=np.std(arr, 1).reshape(2,1)
print(std_r)
Z=Y/std_r
print(Z)

[0.73333333 1.16666667]
[[0.73333333]
 [1.16666667]]
----------------
[[ 0.46666667 -1.03333333  0.56666667]
 [ 0.03333333  0.83333333 -0.86666667]]
0.7455423082115014
[[0.73181661]
 [0.69442222]]
[[ 0.63768253 -1.41201131  0.77432878]
 [ 0.04800154  1.2000384  -1.24803994]]

# Exercice  matrix _ année
## version OK

In [21]:
import pandas as pd
import numpy as np


def init_data():
    FirstName = pd.Series([ 'Jack','Sam','Jenn','Beth'])
    LastName = pd.Series(['Doe','Williams','Smith','Parker'])
    GradYear = pd.Series([2021,2022,2023,2022])
    MeanScore = pd.Series([ 90.6,88.7,74.2,89.5])
    Medianscore = pd.Series([90.0,88.5,75.5,89.1])
    df = pd.DataFrame({'FirstName': FirstName, 'LastName': LastName,'GradYear':GradYear,'MeanScore':MeanScore,'Medianscore':Medianscore })
    return df

def df2matrix(df):
    # Your code goes here
    row,col=df.shape
    array1 = df[df.columns[3:]].to_numpy()
    array2=np.zeros((row,col-2))
    array3 = np.column_stack((array1, array2))
    for i in range(len(df)):
        index_maj=int(str(df.loc[i,'GradYear'])[-1])
        array3[i,index_maj+1]=1
    return array3

In [22]:
my_data=init_data()
print(my_data, '\n')   # Example input
print(df2matrix(my_data))

  FirstName  LastName  GradYear  MeanScore  Medianscore
0      Jack       Doe      2021       90.6         90.0
1       Sam  Williams      2022       88.7         88.5
2      Jenn     Smith      2023       74.2         75.5
3      Beth    Parker      2022       89.5         89.1

[[90.6 90.   1.   0.   0. ]
 [88.7 88.5  0.   1.   0. ]
 [74.2 75.5  0.   0.   1. ]
 [89.5 89.1  0.   1.   0. ]]

# exercice OneHotEncoder

 transactions    mood restrictions   integrations  media  price
0        243243   crash       banned  noIntegration    0.6   9008
1        578123  stable    Regulated         PayPal    0.7  16065
2        351780    good         free  nointegration    0.8  17076
3         34098     NaN    regulated         yandex    0.9  19341
4         34098  Stable         free         Paypal    0.9   4789

In [23]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
dataframe = pd.read_csv("dataframe.csv", sep=",")
dataframe

   transactions    mood restrictions   integrations  media  price
0        243243   crash       banned  noIntegration    0.6   9008
1        578123  stable    Regulated         PayPal    0.7  16065
2        351780    good         free  nointegration    0.8  17076
3         34098     NaN    regulated         yandex    0.9  19341
4         34098  Stable         free         Paypal    0.9   4789

In [24]:
def preprocess(dataframe):
    # Your code goes here
    print(dataframe)
    encoder = OneHotEncoder(sparse=False)
    cols=[ 'mood','restrictions','integrations','d']
    #unique_values = list(dataframe['transactions'].unique())
    one_col=['243243','578123','351780','34098','34098']
    #one_col=dataframe['transactions'].reshape(-1)
    print(one_col)
    one_hot_encod = encoder.fit_transform(dataframe[['transactions']])
    print(one_hot_encod)
    #pd.DataFrame(one_hot_encod, columns=dataframe['transactions'])
    df_new = pd.concat([dataframe['media'], pd.DataFrame(one_hot_encod, columns=[cols])], axis=1)
    return df_new

def preprocess1(df):
    # Your code goes here
    # Utilisons la méthode 'get_dummies' de pandas pour effectuer le one-hot encoding
    cols=[ 'mood','restrictions','integrations']
    one_hot_encod = pd.get_dummies(df[cols])
    df_new = pd.concat([df['transactions'], one_hot_encod], axis=1)
    return df_new

In [25]:
mydataframe = pd.read_csv("dataframe.csv", sep=",")
print(preprocess1(mydataframe))

   transactions  mood_Stable  mood_crash  mood_good  mood_stable  \
0        243243            0           1          0            0
1        578123            0           0          0            1
2        351780            0           0          1            0
3         34098            0           0          0            0
4         34098            1           0          0            0

   restrictions_Regulated  restrictions_banned  restrictions_free  \
0                       0                    1                  0
1                       1                    0                  0
2                       0                    0                  1
3                       0                    0                  0
4                       0                    0                  1

   restrictions_regulated  integrations_PayPal  integrations_Paypal  \
0                       0                    0                    0
1                       0                    1                    0
2                       0                    0                    0
3                       1                    0                    0
4                       0                    0                    1

   integrations_noIntegration  integrations_nointegration  integrations_yandex
0                           1                           0                    0
1                           0                           0                    0
2                           0                           1                    0
3                           0                           0                    1
4                           0                           0                    0

In [26]:
mydataframe = pd.read_csv("dataframe.csv", sep=",")
#print(preprocess1(mydataframe))
print(preprocess(mydataframe))

   transactions    mood restrictions   integrations  media  price
0        243243   crash       banned  noIntegration    0.6   9008
1        578123  stable    Regulated         PayPal    0.7  16065
2        351780    good         free  nointegration    0.8  17076
3         34098     NaN    regulated         yandex    0.9  19341
4         34098  Stable         free         Paypal    0.9   4789
['243243', '578123', '351780', '34098', '34098']
FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
   media  (mood,)  (restrictions,)  (integrations,)  (d,)
0    0.6      0.0              1.0              0.0   0.0
1    0.7      0.0              0.0              0.0   1.0
2    0.8      0.0              0.0              1.0   0.0
3    0.9      1.0              0.0              0.0   0.0
4    0.9      1.0              0.0              0.0   0.0

In [27]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

countries = ['China', 'USA', 'France', 'Italie', 'France']
cities = ['Beijing', 'New York', 'Paris', 'Rome', 'Marseille']

# Imaginons un DataFrame avec les colonnes 'countries' et 'cities' qui contient des valeurs de type string
df = pd.DataFrame({'countries': countries, 'cities': cities})
print(df)
# Créons l'objet OneHotEncoder
encoder = OneHotEncoder(sparse=False)

# Utilisons la méthode 'fit_transform' pour effectuer le one-hot encoding
one_hot_encod = encoder.fit_transform(df[['countries']])
print(one_hot_encod)
# Concaténons la colonne 'cities' avec les données 'countries' encodées en one-hot
df_new = pd.concat([df['cities'], pd.DataFrame(one_hot_encod, columns=['China', 'France', 'Italie', 'USA'])], axis=1)

# Affichons le résultat
df_new

  countries     cities
0     China    Beijing
1       USA   New York
2    France      Paris
3    Italie       Rome
4    France  Marseille
FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]

      cities  China  France  Italie  USA
0    Beijing    1.0     0.0     0.0  0.0
1   New York    0.0     0.0     0.0  1.0
2      Paris    0.0     1.0     0.0  0.0
3       Rome    0.0     0.0     1.0  0.0
4  Marseille    0.0     1.0     0.0  0.0

In [28]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

countries = ['China', 'USA', 'France', 'Italie', 'France']
cities = ['Beijing', 'New York', 'Paris', 'Rome', 'Marseille']

# Imaginons un DataFrame avec les colonnes 'countries' et 'cities' qui contient des valeurs de type string
df = pd.DataFrame({'countries': countries, 'cities': cities})
print(df)
# Créons l'objet OneHotEncoder
encoder = OneHotEncoder(sparse=False)

# Utilisons la méthode 'fit_transform' pour effectuer le one-hot encoding
one_hot_encod = encoder.fit_transform(df[['countries']])

# Concaténons la colonne 'cities' avec les données 'countries' encodées en one-hot
df_new = pd.concat([df['cities'], pd.DataFrame(one_hot_encod, columns=['China', 'France', 'Italie', 'USA'])], axis=1)

# Affichons le résultat
df_new

  countries     cities
0     China    Beijing
1       USA   New York
2    France      Paris
3    Italie       Rome
4    France  Marseille
FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.

      cities  China  France  Italie  USA
0    Beijing    1.0     0.0     0.0  0.0
1   New York    0.0     0.0     0.0  1.0
2      Paris    0.0     1.0     0.0  0.0
3       Rome    0.0     0.0     1.0  0.0
4  Marseille    0.0     1.0     0.0  0.0