TEST IA
2024 : reecriture de pb d'analyse

Sommaire :  

1-[CustomerNAme et Order anonymiser](#CustomerNAme-et-Order-anonymiser)   
2-[Encadrement des outliers](#encadrement-des-outliers)  
3-[rank washing machines](#rank-washing-machines)  
4-[TEST : SENTENCE](#TEST-:-SENTENCE)  
5-[Array normalize](#Array-normalize)  
6-[Exercice  df2_matrix](#Exercice-df2-matrix)  
7-[Exercice OneHotEncoder](#Exercice-OneHotEncoder)  
8-[OneHotEncoder de sklearn](#OneHotEncoder-de-sklearn)

In [2]:
import sys
import traceback
import warnings
import pandas as pd

import warnings

def custom_warning_format(message, category, *args, **kwargs):
    print(f"{category.__name__}: {message}")  # Affiche le type de warning + message seulement

warnings.showwarning = custom_warning_format

def custom_excepthook(exc_type, exc_value, exc_traceback):
    if exc_traceback:
        last_tb = traceback.extract_tb(exc_traceback)[-1]  # Dernière ligne de l'erreur
        print(f"Erreur : {exc_type.__name__}: {exc_value} (ligne {last_tb.lineno})")
    else:
        print(f"Erreur : {exc_type.__name__}: {exc_value}")

#sys.excepthook = custom_excepthook

# exercice 1
## CustomerNAme et Order anonymiser

![Cool code1](./test_mchln/testb1.png)
![Cool code1](test_mchln/testb2.png)
![Cool code1](test_mchln/testb3.png)
![Cool code2](test_mchln/errur_test.png)

In [4]:
# exemple d'update de la serie A en colonne par une autre
import pandas as pd
# Create a DataFrame : 2 series A and B
data = {'A': [1, 2, 3],
        'B': [4, 5, 6]}
df = pd.DataFrame(data)
# Dictionary to update values
update_dict = {'A': [10, 20, 30]}
# Update DataFrame using the dictionary
df.update(pd.DataFrame(update_dict))
print(df)

    A  B
0  10  4
1  20  5
2  30  6

In [5]:
# exemple d'update de la serie A et B en ligne par une autre ligne
# Create a DataFrame
data = {'A': [1, 2, 3],
        'B': [4, 5, 6]}
df = pd.DataFrame(data)

# Dictionary to update values for specific rows
update_dict_rows = {1: {'A': 50, 'B': 60}}

# Update DataFrame using the dictionary
for idx, values in update_dict_rows.items():
    print(idx,values)
    df.loc[idx] = values

print(df)

1 {'A': 50, 'B': 60}
    A   B
0   1   4
1  50  60
2   3   6

In [5]:
# exemple rappel : indice depuis 1 et pas 0
my_list = ['Alex William' ,'Jane Doe', 'John Smith', 'Tom Smith']
my_dict = {}

for index, element in enumerate(my_list):
    my_dict[element] = index+1

print(my_dict)

{'Alex William': 1, 'Jane Doe': 2, 'John Smith': 3, 'Tom Smith': 4}

# version ok

### fonction ano_data:

Utilise unique() et sort() sur des tableaux numpy

Crée des dictionnaires Python classiques

Parcourt deux fois chaque colonne (une pour créer le mapping, une pour appliquer)

### fonction ano_data2:

Utilise des méthodes pandas (drop_duplicates(), sort_values())

Crée des Series pandas comme structures de mapping

Exploite l'indexation pandas

In [7]:
# exercice 1
import pandas as pd
def init_data():
    custo=pd.Series(['John Smith','Tom Smith','Jane Doe','Alex William','John Smith','Jane Doe'])
    order=pd.Series(['Laptop','Router','TV','Laptop','TV','Cable'])
    data=pd.DataFrame({'CustomerName':custo,'Order':order})
    print( "table de code")
    print(custo.drop_duplicates().sort_values())
    new_custo=custo.drop_duplicates().sort_values()
    print(order.drop_duplicates().sort_values())
    print( "-----------------")
    X=custo.drop_duplicates().sort_values()
    print(X.index)
    print( "-----------------")
    print (pd.Series(new_custo.index.values, index=new_custo ))
    print( "-----------------")
    s1 = pd.Series(dict((v,k) for k,v in new_custo.items()))
    print(s1)
    print( "////////////////////////////")
    return data


# ano = rang dans la liste de valeur unique des champs str trié par ordre lexico
def ano_data(df):
    unique_values_cust =df['CustomerName'].unique()
    unique_values_cust.sort()
    my_dict={}
    for index, element in enumerate(unique_values_cust):
        my_dict[element] = index+1
    for idx, values in my_dict.items():
        df.replace(idx, values, inplace=True)
    unique_values_order =df['Order'].unique()
    unique_values_order.sort()
    my_dict={}
    for index, element in enumerate(unique_values_order):
        my_dict[element] = index+1
    for idx, values in my_dict.items():
        df.replace(idx, values, inplace=True)
    return df

#++++++++++++++++
#Alex William 0
#Jane Doe 1
#John Smith 2
#Tom Smith 3
#--------------

# ano = rang dans la liste de valeur unique des champs str trié par ordre lexico
def ano_data2(df):
    new_custo=df['CustomerName'].drop_duplicates().sort_values(ascending=True,ignore_index=True) 
    new_custo_code=pd.Series(new_custo.index.values+1, index=new_custo )
    new_custo_code = new_custo_code[::-1]
    for idx, values in new_custo_code.items():
        df.replace(idx, values, inplace=True) 
    new_order=df['Order'].drop_duplicates().sort_values(ascending=True,ignore_index=True)
    new_order_code=pd.Series(new_order.index.values+1, index=new_order )
    for idx, values in new_order_code.items():
        df.replace(idx, values, inplace=True)
    return df


my_data=init_data()
print( "Data-----------------------")
print(my_data)
print( "RESULTAT ano2-----------------------")
print(ano_data2(my_data))
print( "RESULTAT ano =======================*")
my_data=init_data()
ano_data(my_data)

table de code
3    Alex William
2        Jane Doe
0      John Smith
1       Tom Smith
dtype: object
5     Cable
0    Laptop
1    Router
2        TV
dtype: object
-----------------
Int64Index([3, 2, 0, 1], dtype='int64')
-----------------
Alex William    3
Jane Doe        2
John Smith      0
Tom Smith       1
dtype: int64
-----------------
Alex William    3
Jane Doe        2
John Smith      0
Tom Smith       1
dtype: int64
////////////////////////////
Data-----------------------
   CustomerName   Order
0    John Smith  Laptop
1     Tom Smith  Router
2      Jane Doe      TV
3  Alex William  Laptop
4    John Smith      TV
5      Jane Doe   Cable
RESULTAT ano2-----------------------
   CustomerName  Order
0             3      2
1             4      3
2             2      4
3             1      2
4             3      4
5             2      1
RESULTAT ano =======================*
table de code
3    Alex William
2        Jane Doe
0      John Smith
1       Tom Smith
dtype: object
5     Cable
0    Laptop
1    Router
2        TV
dtype: object
-----------------
Int64Index([3, 2, 0, 1], dtype='int64')
-----------------
Alex William    3
Jane Doe        2
John Smith      0
Tom Smith       1
dtype: int64
-----------------
Alex William    3
Jane Doe        2
John Smith      0
Tom Smith       1
dtype: int64
////////////////////////////

   CustomerName  Order
0             3      2
1             4      3
2             2      4
3             1      2
4             3      4
5             2      1

Une version (IA) encore plus optimisée pourrait utiliser factorize():

Cette version:
Est la plus rapide (une seule passe par colonne)  
Utilise des opérations entièrement vectorisées  
Est plus concise et lisible  
Gère automatiquement le tri et les doublons

Performance comparée  
Méthode	Temps (sur 100k rows)	Lisibilité	Maintien ordre  
ano_data	~2.5s	Moyenne	Oui  
ano_data2	~1.8s	Complexe	Oui  
optimized	~0.02s	Excellente	Oui

In [9]:
def ano_data_optimized(df):
    # CustomerName encoding (sorted alphabetically)
    customers = df['CustomerName'].drop_duplicates().sort_values()
    cust_map = {name: i+1 for i, name in enumerate(customers)}
    
    # Order encoding (sorted alphabetically)
    orders = df['Order'].drop_duplicates().sort_values()
    order_map = {name: i+1 for i, name in enumerate(orders)}
    
    df['CustomerName'] = df['CustomerName'].map(cust_map)
    df['Order'] = df['Order'].map(order_map)
    return df
my_data=init_data()
ano_data_optimized(my_data)

table de code
3    Alex William
2        Jane Doe
0      John Smith
1       Tom Smith
dtype: object
5     Cable
0    Laptop
1    Router
2        TV
dtype: object
-----------------
Int64Index([3, 2, 0, 1], dtype='int64')
-----------------
Alex William    3
Jane Doe        2
John Smith      0
Tom Smith       1
dtype: int64
-----------------
Alex William    3
Jane Doe        2
John Smith      0
Tom Smith       1
dtype: int64
////////////////////////////

   CustomerName  Order
0             3      2
1             4      3
2             2      4
3             1      2
4             3      4
5             2      1

In [11]:
# version bidirectionnelle !
def ano_data_bidir(df):
    df = df.copy()
    mappings = {}

    # CustomerName
    customer_cat = df['CustomerName'].astype('category')
    df['CustomerName'] = customer_cat.cat.codes + 1
    mappings['CustomerName'] = {
        'to_code': dict(zip(customer_cat.cat.categories, range(1, len(customer_cat.cat.categories)+1))),
        'to_value': dict(zip(range(1, len(customer_cat.cat.categories)+1), customer_cat.cat.categories))
    }

    # Order
    order_cat = df['Order'].astype('category')
    df['Order'] = order_cat.cat.codes + 1
    mappings['Order'] = {
        'to_code': dict(zip(order_cat.cat.categories, range(1, len(order_cat.cat.categories)+1))),
        'to_value': dict(zip(range(1, len(order_cat.cat.categories)+1), order_cat.cat.categories))
    }

    return df, mappings

In [15]:
my_data=init_data()
df_anon, maps = ano_data_bidir(my_data)

# Pour retrouver les noms de clients :
df_anon['CustomerName'].map(maps['CustomerName']['to_value'])

table de code
3    Alex William
2        Jane Doe
0      John Smith
1       Tom Smith
dtype: object
5     Cable
0    Laptop
1    Router
2        TV
dtype: object
-----------------
Int64Index([3, 2, 0, 1], dtype='int64')
-----------------
Alex William    3
Jane Doe        2
John Smith      0
Tom Smith       1
dtype: int64
-----------------
Alex William    3
Jane Doe        2
John Smith      0
Tom Smith       1
dtype: int64
////////////////////////////

0      John Smith
1       Tom Smith
2        Jane Doe
3    Alex William
4      John Smith
5        Jane Doe
Name: CustomerName, dtype: object

In [14]:
# Pour retrouver les ordres :
df_anon['Order'].map(maps['Order']['to_value'])

0    Laptop
1    Router
2        TV
3    Laptop
4        TV
5     Cable
Name: Order, dtype: object

Ce que ça fait de mieux :
💡	Explication
.map(...)	Plus rapide que .replace() dans une boucle
drop_duplicates().sort_values()	T’identifie les valeurs uniques triées
ignore_index=True	T’évite d’avoir des index troublants
range(1, N+1)	Donne les codes à partir de 1
pd.Series(..., index=...)	Crée un mapping propre entre valeur ➝ code

In [17]:
# autre version avec map et uniquement des series pandas  
def ano_data_map(df):
    df = df.copy()  # pour ne pas modifier l'original

    # Mapping CustomerName ➝ code
    unique_custo = df['CustomerName'].drop_duplicates().sort_values(ignore_index=True)
    custo_map = pd.Series(data=range(1, len(unique_custo)+1), index=unique_custo)
    df['CustomerName'] = df['CustomerName'].map(custo_map)

    # Mapping Order ➝ code
    unique_order = df['Order'].drop_duplicates().sort_values(ignore_index=True)
    order_map = pd.Series(data=range(1, len(unique_order)+1), index=unique_order)
    df['Order'] = df['Order'].map(order_map)

    return df

my_data=init_data()
ano_data_map(my_data)

table de code
3    Alex William
2        Jane Doe
0      John Smith
1       Tom Smith
dtype: object
5     Cable
0    Laptop
1    Router
2        TV
dtype: object
-----------------
Int64Index([3, 2, 0, 1], dtype='int64')
-----------------
Alex William    3
Jane Doe        2
John Smith      0
Tom Smith       1
dtype: int64
-----------------
Alex William    3
Jane Doe        2
John Smith      0
Tom Smith       1
dtype: int64
////////////////////////////

   CustomerName  Order
0             3      2
1             4      3
2             2      4
3             1      2
4             3      4
5             2      1

# EXERCICE 2
## encadrement des outliers
remplacer les valeurs aberrantes par les formules:

Q3 + 1.5 * IQR > outlier > Q1 -1.5 * IQR

Q1,Q3= df.ma_var.quantile([0.25,0.75])
IQR= Q3-Q1

In [18]:
# EXERCICE 2

def init_data():
    C1 = pd.Series([-21.57,1.24,-0.84,32.35,0.82,-3.11,0.46,-18.68,0.04,30.87])
    C2 = pd.Series([2.49,  2.27,0.25 ,-2.33,-2.91,-3.61,0.58,-2.59,-3.99,1.54])
    C3 = pd.Series([1.14,4.76,14.23,-2.65,-3.53,-0.03,17.5,-0.21,2.96,2.31])
    data = pd.DataFrame({'C1': C1, 'C2': C2, 'C3': C3})
    return data
init_data()

      C1    C2     C3
0 -21.57  2.49   1.14
1   1.24  2.27   4.76
2  -0.84  0.25  14.23
3  32.35 -2.33  -2.65
4   0.82 -2.91  -3.53
5  -3.11 -3.61  -0.03
6   0.46  0.58  17.50
7 -18.68 -2.59  -0.21
8   0.04 -3.99   2.96
9  30.87  1.54   2.31

Valeur manquantes :

Df. dropna()
Df.dropna ( subset= ..)

Df.fillna("0")
Df.dropna ( subset= ..).fillna("0")

Df[col].fillna(df[col].mean() ]

df.isnull().mean().sort_values(ascending=False)
---------------------------------------------------
Q3 + 1.5 * IQR > outlier > Q1 -1.5 * IQR

Q1,Q3= df.ma_var.quantile([0.25,0.75])
IQR= Q3-Q1

# condition
df2=df.loc[(df['Discount'] >= 1000) & (df['Discount'] <= 2000)]

# Replace values of columns by using DataFrame.loc[] property.
df.loc[df['Fee'] > 22000, 'Fee'] = 15000

In [19]:
def handle_col(df,coll):
    newdf = df.copy()
    print(coll)
    Q1,Q3= df.loc[:,coll].quantile([0.25,0.75])
    IQR= Q3-Q1
    lim_inf=Q1-1.5*IQR
    lim_sup=Q3+1.5*IQR
    print(Q1,Q3,IQR,lim_inf,lim_sup)
    # premier sup a lim_inf
    min_no=df.loc[(df.loc[:,coll] >= lim_inf)].min()
    min_no_Col=min_no[coll]
    print("min",min_no)
    print(min_no[coll])
    # premier inf a lim_sup
    max_no=df.loc[(df.loc[:,coll] <= lim_sup)].max()
    print("/////",max_no)
    max_no_Col=max_no[coll]
    print("max",max_no)
    print("---",max_no[coll])
    df.loc[df.loc[:,coll] < lim_inf, coll]=min_no_Col
    df.loc[df.loc[:,coll] > lim_sup, coll]=max_no_Col
    print(df)
def handle_outliers(df):
    handle_col(df,'C1')
    handle_col(df,'C2')
    handle_col(df,'C3')
    
my_data=init_data()
print(my_data)
handle_outliers(my_data)

      C1    C2     C3
0 -21.57  2.49   1.14
1   1.24  2.27   4.76
2  -0.84  0.25  14.23
3  32.35 -2.33  -2.65
4   0.82 -2.91  -3.53
5  -3.11 -3.61  -0.03
6   0.46  0.58  17.50
7 -18.68 -2.59  -0.21
8   0.04 -3.99   2.96
9  30.87  1.54   2.31
C1
-2.5425 1.135 3.6775 -8.05875 6.65125
min C1   -3.11
C2   -3.99
C3   -3.53
dtype: float64
-3.11
///// C1     1.24
C2     2.49
C3    17.50
dtype: float64
max C1     1.24
C2     2.49
C3    17.50
dtype: float64
--- 1.24
     C1    C2     C3
0 -3.11  2.49   1.14
1  1.24  2.27   4.76
2 -0.84  0.25  14.23
3  1.24 -2.33  -2.65
4  0.82 -2.91  -3.53
5 -3.11 -3.61  -0.03
6  0.46  0.58  17.50
7 -3.11 -2.59  -0.21
8  0.04 -3.99   2.96
9  1.24  1.54   2.31
C2
-2.83 1.3 4.13 -9.025 7.495
min C1   -3.11
C2   -3.99
C3   -3.53
dtype: float64
-3.99
///// C1     1.24
C2     2.49
C3    17.50
dtype: float64
max C1     1.24
C2     2.49
C3    17.50
dtype: float64
--- 2.49
     C1    C2     C3
0 -3.11  2.49   1.14
1  1.24  2.27   4.76
2 -0.84  0.25  14.23
3  1.24 -2.33  -2.65
4  0.82 -2.91  -3.53
5 -3.11 -3.61  -0.03
6  0.46  0.58  17.50
7 -3.11 -2.59  -0.21
8  0.04 -3.99   2.96
9  1.24  1.54   2.31
C3
-0.16499999999999998 4.31 4.475 -6.8774999999999995 11.022499999999999
min C1   -3.11
C2   -3.99
C3   -3.53
dtype: float64
-3.53
///// C1    1.24
C2    2.49
C3    4.76
dtype: float64
max C1    1.24
C2    2.49
C3    4.76
dtype: float64
--- 4.76
     C1    C2    C3
0 -3.11  2.49  1.14
1  1.24  2.27  4.76
2 -0.84  0.25  4.76
3  1.24 -2.33 -2.65
4  0.82 -2.91 -3.53
5 -3.11 -3.61 -0.03
6  0.46  0.58  4.76
7 -3.11 -2.59 -0.21
8  0.04 -3.99  2.96
9  1.24  1.54  2.31

# version OK

In [20]:
def handle_col(df,coll):
    Q1,Q3= df.loc[:,coll].quantile([0.25,0.75])
    IQR= Q3-Q1
    lim_inf=Q1-1.5*IQR
    lim_sup=Q3+1.5*IQR
    # premier sup a lim_inf
    min_no=df.loc[(df.loc[:,coll] >= lim_inf)].min()
    min_no_Col=min_no[coll]
    # premier inf a lim_sup
    max_no=df.loc[(df.loc[:,coll] <= lim_sup)].max()
    max_no_Col=max_no[coll]
    df.loc[df.loc[:,coll] < lim_inf, coll]=min_no_Col
    df.loc[df.loc[:,coll] > lim_sup, coll]=max_no_Col
    return df

def handle_outliers(df):
    handle_col(df,'C1')
    handle_col(df,'C2')
    handle_col(df,'C3')
    return df

my_data=init_data()
print(my_data)
handle_outliers(my_data)

      C1    C2     C3
0 -21.57  2.49   1.14
1   1.24  2.27   4.76
2  -0.84  0.25  14.23
3  32.35 -2.33  -2.65
4   0.82 -2.91  -3.53
5  -3.11 -3.61  -0.03
6   0.46  0.58  17.50
7 -18.68 -2.59  -0.21
8   0.04 -3.99   2.96
9  30.87  1.54   2.31

     C1    C2    C3
0 -3.11  2.49  1.14
1  1.24  2.27  4.76
2 -0.84  0.25  4.76
3  1.24 -2.33 -2.65
4  0.82 -2.91 -3.53
5 -3.11 -3.61 -0.03
6  0.46  0.58  4.76
7 -3.11 -2.59 -0.21
8  0.04 -3.99  2.96
9  1.24  1.54  2.31

Remarque :

clip(lower=X, upper=Y) tronque les valeurs en dehors de [X, Y].
.clip() pour remplacer automatiquement
Ici on remplace les outliers avec les valeurs extrêmes non-outliers,

In [22]:
# version toutes colonnes
def handle_cols(df, cols):
    df = df.copy()
    for col in cols:
        Q1, Q3 = df[col].quantile([0.25, 0.75])
        IQR = Q3 - Q1
        lim_inf, lim_sup = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR

        min_no_col = df.loc[df[col] >= lim_inf, col].min()
        max_no_col = df.loc[df[col] <= lim_sup, col].max()

        df[col] = df[col].clip(lower=min_no_col, upper=max_no_col)

    return df
df = init_data()
df_clean = handle_cols(df, ['C1', 'C2', 'C3'])
#df_clean = handle_cols(df, df.columns)  # toutes les colonnes
df_clean

     C1    C2    C3
0 -3.11  2.49  1.14
1  1.24  2.27  4.76
2 -0.84  0.25  4.76
3  1.24 -2.33 -2.65
4  0.82 -2.91 -3.53
5 -3.11 -3.61 -0.03
6  0.46  0.58  4.76
7 -3.11 -2.59 -0.21
8  0.04 -3.99  2.96
9  1.24  1.54  2.31

In [23]:
# version tracking des valeurs remplacées
def handle_cols_verbose(df, cols):
    df = df.copy()
    outliers_report = {}

    for col in cols:
        Q1, Q3 = df[col].quantile([0.25, 0.75])
        IQR = Q3 - Q1
        lim_inf, lim_sup = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR

        # Repères de remplacement
        min_no_col = df.loc[df[col] >= lim_inf, col].min()
        max_no_col = df.loc[df[col] <= lim_sup, col].max()

        # Enregistrer les outliers
        outliers = df.loc[(df[col] < lim_inf) | (df[col] > lim_sup), col]
        outliers_report[col] = {
            'count': len(outliers),
            'values': outliers.values.tolist(),
            'lim_inf': lim_inf,
            'lim_sup': lim_sup,
            'replacement_min': min_no_col,
            'replacement_max': max_no_col
        }

        # Apaiser les excès
        df[col] = df[col].clip(lower=min_no_col, upper=max_no_col)

    return df, outliers_report
df = init_data()
df_clean, report = handle_cols_verbose(df, df.columns)

# Et pour lire le rapport :
from pprint import pprint
pprint(report)

{'C1': {'count': 4,
        'lim_inf': -8.05875,
        'lim_sup': 6.65125,
        'replacement_max': 1.24,
        'replacement_min': -3.11,
        'values': [-21.57, 32.35, -18.68, 30.87]},
 'C2': {'count': 0,
        'lim_inf': -9.025,
        'lim_sup': 7.495,
        'replacement_max': 2.49,
        'replacement_min': -3.99,
        'values': []},
 'C3': {'count': 2,
        'lim_inf': -6.8774999999999995,
        'lim_sup': 11.022499999999999,
        'replacement_max': 4.76,
        'replacement_min': -3.53,
        'values': [14.23, 17.5]}}

# Exercice 3
## rank washing machines

- valeur unique + score moyen + trié par prix croissant + ordre maintenu des indices + valeur nan
- jointure entre df

![wCool code22](test_mchln/pb_pd2.png)
![wCool code23](test_mchln/pb_pd3.png)
![wCool code21](test_mchln/pb_pd1.png)
![wCool code24](test_mchln/pb_pd4.png)

In [26]:
def init_data3():
    BrandName_S = pd.Series([ 'Lowell','Lowell','Purewash','Wilson','Purewash','Purewash','Lowell','Wilson','Lowell','Wilson','Purewash','Wilson'])
    Score_S = pd.Series([0.743,0.741,0.784,float('nan'),0.968,0.840,float('nan'),float('nan'),0.451,0.739,0.539,0.485])
    scores_df = pd.DataFrame({'BrandName': BrandName_S, 'Score': Score_S })
    BrandName_S2 = pd.Series([ 'Lowell','Purewash','Wilson'])
    Price_S2 = pd.Series([135.75,122.61,113.67])
    prices_df = pd.DataFrame({'BrandName': BrandName_S2, 'Price': Price_S2 })
    return scores_df,prices_df
init_data3()

(   BrandName  Score
 0     Lowell  0.743
 1     Lowell  0.741
 2   Purewash  0.784
 3     Wilson    NaN
 4   Purewash  0.968
 5   Purewash  0.840
 6     Lowell    NaN
 7     Wilson    NaN
 8     Lowell  0.451
 9     Wilson  0.739
 10  Purewash  0.539
 11    Wilson  0.485,
   BrandName   Price
 0    Lowell  135.75
 1  Purewash  122.61
 2    Wilson  113.67)

# version OK 
## score, price et Brandname machine wash

In [27]:
def rank_washing_machines(scores_df, prices_df):
    # Your code goes here
    # Calcule le score moyen (AvgScore) par marque.
    new_df=(scores_df.groupby('BrandName')['Score'].mean()).reset_index()
    # Fait une jointure interne avec le DataFrame des prix, pour ne garder que les marques communes aux deux tableaux.
    new_df=new_df.rename(columns={'Score':'AvgScore'})
    inner_merged_df = new_df.merge(
      prices_df,
      left_on = ["BrandName"],
      right_on = ["BrandName"],
      how = "inner"
    )
    #Calcule un prix ajusté = prix divisé par score moyen : plus il est petit, meilleur est le rapport qualité/prix.
    inner_merged_df['prix_aj']=inner_merged_df['Price']/inner_merged_df['AvgScore']
    #Trie du meilleur rapport qualité/prix au moins bon.
    inner_merged_df=inner_merged_df.sort_values('prix_aj', ascending = True,ignore_index=True)
    #Supprime la colonne intermédiaire une fois le tri effectué.
    inner_merged_df=inner_merged_df.drop(['prix_aj'], axis=1)
    #Réorganise les colonnes dans l’ordre souhaité.
    columns_titles = ["BrandName","Price","AvgScore"]
    inner_merged_df=inner_merged_df.reindex(columns=columns_titles)
    return inner_merged_df

In [28]:
scores_df1, prices_df1=init_data3()
rank_washing_machines(scores_df1, prices_df1)

  BrandName   Price  AvgScore
0  Purewash  122.61   0.78275
1    Wilson  113.67   0.61200
2    Lowell  135.75   0.64500

attention : il faut des indices ordonnés dixit enoncé  
Avec ignore_index=True 🟢	 Index remis à 0,1,2…
	
Sans ignore_index=True 🔴    Index d’origine conservé

In [31]:
def rank_washing_machines(scores_df, prices_df): 
    # Calcul du score moyen par marque
    avg_scores = scores_df.groupby("BrandName", as_index=False)["Score"].mean()
    avg_scores.rename(columns={"Score": "AvgScore"}, inplace=True)

    # Jointure avec les prix
    merged_df = avg_scores.merge(prices_df, on="BrandName", how="inner")

    # Tri par rapport qualité/prix
    merged_df["Ratio"] = merged_df["Price"] / merged_df["AvgScore"]
    ranked_df = merged_df.sort_values("Ratio", ascending=True, ignore_index=True)

    # Nettoyage et sélection finale des colonnes
    return ranked_df[["BrandName", "Price", "AvgScore"]]
scores_df1, prices_df1=init_data3()
rank_washing_machines(scores_df1, prices_df1)

  BrandName   Price  AvgScore
0  Purewash  122.61   0.78275
1    Wilson  113.67   0.61200
2    Lowell  135.75   0.64500

# TEST : SENTENCE

suppression + remplacement + mapping (mot:place)

![wCool code22](test_mchln/capture_test1.png)
![wCool code23](test_mchln/test2.png)

# Version OK

In [37]:
def tokenize_sentence(sentence):
    punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    # supprimer la ponctuation
    for ele in sentence:
        if ele in punc:
            sentence = sentence.replace(ele, "")
    # separe les mots
    new_sentence1=sentence.split()
    new_sentence2_set=set(new_sentence1)
    new_sentence2 = [e for e in new_sentence2_set]
    # tri des mots
    new_sentence2.sort() 
    print(new_sentence2)
    # construit la liste des indices depuis la premiere phrase
    answer=[new_sentence2.index(e) for e in new_sentence1]
    return answer

In [38]:
sentence = 'they know her , jill . but she does not know them .'
sentence_bis = 'we came , we saw , we conquered .' 
sentence_ter = 'square : a shape that is a rectangle'

print(sentence, '\n')   # Example input
print(tokenize_sentence(sentence))

they know her , jill . but she does not know them .

['but', 'does', 'her', 'jill', 'know', 'not', 'she', 'them', 'they']
[8, 4, 2, 3, 0, 6, 1, 5, 4, 7]

In [39]:
sentence_bis = 'we came , we saw , we conquered .' 
print(tokenize_sentence(sentence_bis))

['came', 'conquered', 'saw', 'we']
[3, 0, 3, 2, 3, 1]

In [40]:
sentence_ter = 'square : a shape that is a rectangle'
print(tokenize_sentence(sentence_ter))

['a', 'is', 'rectangle', 'shape', 'square', 'that']
[4, 0, 3, 5, 1, 0, 2]

In [42]:
# autre version : dico
import string

def tokenize_sentence(sentence):
    # Supprimer ponctuation (plus efficace)
    translator = str.maketrans('', '', string.punctuation)
    cleaned = sentence.translate(translator)

    # Séparer en mots
    words = cleaned.split()

    # Créer un mapping mot -> index (trié)
    unique_sorted_words = sorted(set(words))
    print(unique_sorted_words)
    word_to_index = {word: idx for idx, word in enumerate(unique_sorted_words)}
    print(word_to_index)
    # Créer la liste de tokens
    tokens = [word_to_index[word] for word in words]

    return tokens
print(tokenize_sentence(sentence))

['but', 'does', 'her', 'jill', 'know', 'not', 'she', 'them', 'they']
{'but': 0, 'does': 1, 'her': 2, 'jill': 3, 'know': 4, 'not': 5, 'she': 6, 'them': 7, 'they': 8}
[8, 4, 2, 3, 0, 6, 1, 5, 4, 7]

# Array normalize

divison par zero + mask logique + rempalcement valeur + pb dimension  (broadcasting)

![wCool code22](test_mchln/test-a1.png)
![wCool code23](test_mchln/test-a2.png)
![wCool code23](test_mchln/test-X.png)
![wCool code23](test_mchln/test-Y.png)

# version OK

In [46]:
# version warning si std=0
import numpy as np
def standardize_data(arr):
    # Your code goes here
    # Calcule la moyenne de chaque ligne.axis=1 → on réduit les colonnes.
    centre_gravite = np.mean(arr, axis=1)
    #On remet la moyenne en colonne pour la soustraction.
    row,_l=arr.shape
    #print(row,col)
    cg_r=centre_gravite.reshape(row,1)
    
    # Centrage : soustrait la moyenne à chaque élément de la ligne
    Y=arr-cg_r
    # Divise chaque valeur par l’écart-type → standardisation.
    # On obtient des valeurs avec moyenne 0 et écart-type 1.
    std_r=np.std(arr, 1).reshape(row,1)
    # NumPy tente la division par zéro, ce qui produit déjà des NaN, 
    # et déclenche l'avertissement RuntimeWarning: invalid value encountered in divide.
    Z=Y/std_r
    # si ecart type =0 => mettre valeur np.inf a la place de nan
    # Si l’écart-type est 0 (ligne constante), on a une division par 0 → NaN.
    # remplacer ces NaN par inf.
    Z[np.isnan(Z)] = np.inf
    return Z

In [47]:
# WARNING
arr = np.array([
    [1.2, -0.3, 1.3],
    [1.2, 2., 0.3]
]).astype(np.float64)

arr_bis = np.array([
  [10.3, 0.5, -1.2],
  [1., 1., 1.],
  [-5.4, 10., 1.]
]).astype(np.float64)

arr_ter = np.array([
  [7.2, 1.1, -14., 10.3],
  [2.2, 0., 0.4, 9.9]
]).astype(np.float64)


print(arr, '\n')   # Example input
print(standardize_data(arr))
print(standardize_data(arr_bis))
print(standardize_data(arr_ter))

[[ 1.2 -0.3  1.3]
 [ 1.2  2.   0.3]]

[[ 0.63768253 -1.41201131  0.77432878]
 [ 0.04800154  1.2000384  -1.24803994]]
[[ 1.40089141 -0.53273335 -0.86815806]
 [        inf         inf         inf]
 [-1.15036775  1.28756757 -0.13719982]]
[[ 0.64691084 -0.00534637 -1.6199503   0.97838582]
 [-0.23134491 -0.78157063 -0.68152959  1.69444513]]

C:\Users\jphal\AppData\Local\Temp\ipykernel_9072\2525121530.py:16: RuntimeWarning: invalid value encountered in divide
  Z=Y/std_r

In [45]:
arr = np.array([
    [1.2, -0.3, 1.3],
    [1.2, 2., 0.3]
]).astype(np.float64)
centre_gravite = np.mean(arr, axis=1)
print(centre_gravite)
print(centre_gravite.reshape(2,1))
cg_r=centre_gravite.reshape(2,1)
print('----------------')
#mat_centre= np.hstack([centre_gravite] *2).reshape (2,2)
#print(mat_centre)
Y=arr-cg_r
print(Y)
ecarts_types = np.std(arr)
print(ecarts_types)
std_r=np.std(arr, 1).reshape(2,1)
print(std_r)
Z=Y/std_r
print(Z)

[0.73333333 1.16666667]
[[0.73333333]
 [1.16666667]]
----------------
[[ 0.46666667 -1.03333333  0.56666667]
 [ 0.03333333  0.83333333 -0.86666667]]
0.7455423082115014
[[0.73181661]
 [0.69442222]]
[[ 0.63768253 -1.41201131  0.77432878]
 [ 0.04800154  1.2000384  -1.24803994]]

une matrice arr de forme (n, m) — n lignes (lignes de données), m colonnes (features).
Tu veux standardiser ligne par ligne (z-score), mais certaines lignes ont un écart-type nul (= constantes).
On veut donc remplacer toute la ligne par np.inf dans ce cas.
pb de dimension : il faut repliquer les True / false et remplacer les True par inf (mask)

# Supposons m = 3
mask = [[False], [True], [False]]
mask_full = [[False, False, False],
             [True,  True,  True],
             [False, False, False]]

stds      → shape (n,1)       → [[1.], [0.], [2.]]
mask      → shape (n,1)       → [[False], [True], [False]]
repeat    → shape (n,m)       → [[False, False, False],
                                 [True,  True,  True],
                                 [False, False, False]]
Z[mask_full] = np.inf         → ligne 2 remplacée par infs

In [55]:
# VERSION SANS WARNING DE DIV ZERO : on remplace 0 par 1 temporairement
import numpy as np

import numpy as np

import numpy as np

def standardize_data(arr):
    means = np.mean(arr, axis=1, keepdims=True)              # (n,1)
    stds = np.std(arr, axis=1, keepdims=True)                # (n,1)
    stds_safe = np.where(stds == 0, 1, stds)                 # (n,1)

    Z = (arr - means) / stds_safe                            # (n,m)

    # masque logique 2D (n,1) → on le répète pour correspondre à Z (n,m)
    mask = (stds == 0)
    print( mask)
    # Étendre le masque (broadcasting manquant)
    # mask est (n,1) → on le réplique horizontalement autant de fois qu’il y a de colonnes.
    # mask_full devient (n, m), comme Z.
    mask_full = np.repeat(mask, arr.shape[1], axis=1) 
    print(mask_full)# (n,m)
    # partout ou c'est True je remplace
    Z[mask_full] = np.inf

    return Z

arr = np.array([
    [1, 2, 3],      # std != 0
    [4, 4, 4],      # std == 0
    [10, 20, 30]    # std != 0
])
print(standardize_data(arr))

[[False]
 [ True]
 [False]]
[[False False False]
 [ True  True  True]
 [False False False]]
[[-1.22474487  0.          1.22474487]
 [        inf         inf         inf]
 [-1.22474487  0.          1.22474487]]

In [56]:
#Version sans masque logique — avec np.where
import numpy as np

def standardize_data(arr):
    means = np.mean(arr, axis=1, keepdims=True)
    stds = np.std(arr, axis=1, keepdims=True)

    # Empêche la division par zéro : on remplace les zéros par 1 temporairement
    stds_safe = np.where(stds == 0, 1, stds)

    Z = (arr - means) / stds_safe

    # Là où std était 0 → on met np.inf
    Z = np.where(stds == 0, np.inf, Z)

    return Z
print(standardize_data(arr))

[[-1.22474487  0.          1.22474487]
 [        inf         inf         inf]
 [-1.22474487  0.          1.22474487]]

In [63]:
# version boucle sur ligne et colonne a l'ancienne
import numpy as np

def standardize_data_lowtech(arr):
    # on veut un np.ndarray , on se premuni des listes de liste
    arr = np.array(arr)  # au cas où on reçoit une liste
    n_rows, n_cols = arr.shape
    Z = np.empty_like(arr, dtype=float)
    # boucle sur les lignes
    for i in range(n_rows):
        row = arr[i]
        mean = np.mean(row)
        std = np.std(row)

        if std == 0:
            Z[i] = np.full(n_cols, np.inf)  # tous les éléments deviennent inf
        else:
            Z[i] = (row - mean) / std

    return Z
arr = np.array([
    [1.2, -0.3, 1.3],
    [1.2, 2., 0.3]
]).astype(np.float64)

print(standardize_data(arr))
arr = np.array([[1, 2], [3, 4]])
print(standardize_data_lowtech(arr))
# cas probematique : ca passe qd meme
arr = [[1, 2], [3, 4]]
standardize_data_lowtech(arr)

[[ 0.63768253 -1.41201131  0.77432878]
 [ 0.04800154  1.2000384  -1.24803994]]
[[-1.  1.]
 [-1.  1.]]

array([[-1.,  1.],
       [-1.,  1.]])

# Exercice df2-matrix

manipualtion de df + lignes identifiants + colonne de pki / indicateur

![wCool code22](test_mchln/test_m1.png)
![wCool code23](test_mchln/test_m2.png)

In [65]:
#version initiale ok
import pandas as pd
import numpy as np


def init_data():
    FirstName = pd.Series([ 'Jack','Sam','Jenn','Beth'])
    LastName = pd.Series(['Doe','Williams','Smith','Parker'])
    GradYear = pd.Series([2021,2022,2023,2022])
    MeanScore = pd.Series([ 90.6,88.7,74.2,89.5])
    Medianscore = pd.Series([90.0,88.5,75.5,89.1])
    df = pd.DataFrame({'FirstName': FirstName, 'LastName': LastName,'GradYear':GradYear,'MeanScore':MeanScore,'Medianscore':Medianscore })
    return df

def df2matrix(df):
    # Your code goes here
    row,col=df.shape
    array1 = df[df.columns[3:]].to_numpy()
    array2=np.zeros((row,col-2))
    array3 = np.column_stack((array1, array2))
    for i in range(len(df)):
        index_maj=int(str(df.loc[i,'GradYear'])[-1])
        array3[i,index_maj+1]=1
    return array3

In [66]:
my_data=init_data()
print(my_data, '\n')   # Example input
print(df2matrix(my_data))

  FirstName  LastName  GradYear  MeanScore  Medianscore
0      Jack       Doe      2021       90.6         90.0
1       Sam  Williams      2022       88.7         88.5
2      Jenn     Smith      2023       74.2         75.5
3      Beth    Parker      2022       89.5         89.1

[[90.6 90.   1.   0.   0. ]
 [88.7 88.5  0.   1.   0. ]
 [74.2 75.5  0.   0.   1. ]
 [89.5 89.1  0.   1.   0. ]]

In [74]:
# version :
# version 0 : get_dummies + hstack
# version : score auto nom colonne + hstack
def init_data():
    FirstName = pd.Series(['Jack', 'Sam', 'Jenn', 'Beth'])
    LastName = pd.Series(['Doe', 'Williams', 'Smith', 'Parker'])
    GradYear = pd.Series([2021, 2022, 2023, 2022])
    MeanScore = pd.Series([90.6, 88.7, 74.2, 89.5])
    MedianScore = pd.Series([90.0, 88.5, 75.5, 89.1])
    df = pd.DataFrame({
        'FirstName': FirstName,
        'LastName': LastName,
        'GradYear': GradYear,
        'MeanScore': MeanScore,
        'MedianScore': MedianScore
    })
    return df

def df2matrix0(df):
    # Extraire les colonnes de scores
    score_data = df[['MeanScore', 'MedianScore']].to_numpy()

    # Encodage one-hot de GradYear (2021, 2022, 2023 → 3 colonnes)
    grad_year_encoded = pd.get_dummies(df['GradYear'], dtype=float)

    # Conversion en numpy array
    grad_year_array = grad_year_encoded.to_numpy()

    # Combinaison scores + one-hot GradYear
    final_matrix = np.hstack([score_data, grad_year_array])
    return final_matrix

def df2matrix(df):
    score_cols = [col for col in df.columns if 'Score' in col]  # récupère automatiquement les scores
    score_data = df[score_cols].to_numpy()

    grad_years = [2021, 2022, 2023]
    grad_year_encoded = pd.get_dummies(df['GradYear'], dtype=float).reindex(columns=grad_years, fill_value=0)
    grad_year_array = grad_year_encoded.to_numpy()

    final_matrix = np.hstack([score_data, grad_year_array])
    return final_matrix



my_data=init_data()
print(my_data, '\n')   # Example input
print(df2matrix(my_data))
print(df2matrix0(my_data))

  FirstName  LastName  GradYear  MeanScore  MedianScore
0      Jack       Doe      2021       90.6         90.0
1       Sam  Williams      2022       88.7         88.5
2      Jenn     Smith      2023       74.2         75.5
3      Beth    Parker      2022       89.5         89.1

[[90.6 90.   1.   0.   0. ]
 [88.7 88.5  0.   1.   0. ]
 [74.2 75.5  0.   0.   1. ]
 [89.5 89.1  0.   1.   0. ]]
[[90.6 90.   1.   0.   0. ]
 [88.7 88.5  0.   1.   0. ]
 [74.2 75.5  0.   0.   1. ]
 [89.5 89.1  0.   1.   0. ]]

In [69]:
# version : dernier chiffre significatif + get_dummies + concat (concis++)
def df2matrix_v2(df):
    df['GradYearLastDigit'] = df['GradYear'] % 10
    encoded = pd.get_dummies(df['GradYearLastDigit'], prefix="GradDigit")
    score_data = df[['MeanScore', 'MedianScore']]
    return pd.concat([score_data, encoded], axis=1).to_numpy()

my_data=init_data()
print(my_data, '\n')   # Example input
print(df2matrix_v2(my_data))

  FirstName  LastName  GradYear  MeanScore  MedianScore
0      Jack       Doe      2021       90.6         90.0
1       Sam  Williams      2022       88.7         88.5
2      Jenn     Smith      2023       74.2         75.5
3      Beth    Parker      2022       89.5         89.1

[[90.6 90.   1.   0.   0. ]
 [88.7 88.5  0.   1.   0. ]
 [74.2 75.5  0.   0.   1. ]
 [89.5 89.1  0.   1.   0. ]]

In [75]:
# version boucle sur ligne + last digit
def df2matrix_v3(df):
    row, col = df.shape
    
    # Récupérer les colonnes de score (ici colonnes 2 et 3 = MeanScore, MedianScore)
    score_data = df.iloc[:, 3:5].to_numpy()  # Colonnes index 3 et 4
    
    # Créer une matrice à zéros pour accueillir le codage (GradYear etc.)
    num_extra_cols = col - 3  # 1 colonne pour GradYear en plus des scores
    extra_data = np.zeros((row, num_extra_cols))
    
    # Fusion : scores + colonnes codées à 0
    matrix = np.column_stack((score_data, extra_data))
    
    # Encodage basé sur le dernier chiffre de GradYear
    for i in range(row):
        year = df.loc[i, 'GradYear']
        last_digit = int(str(year)[-1])  # ou year % 10
        if last_digit < num_extra_cols:
            matrix[i, last_digit + 2] = 1  # +2 pour décaler après 2 colonnes de score
    
    return matrix
my_data=init_data()
print(my_data, '\n')   # Example input
print(df2matrix_v3(my_data))

  FirstName  LastName  GradYear  MeanScore  MedianScore
0      Jack       Doe      2021       90.6         90.0
1       Sam  Williams      2022       88.7         88.5
2      Jenn     Smith      2023       74.2         75.5
3      Beth    Parker      2022       89.5         89.1

[[90.6 90.   0.   1. ]
 [88.7 88.5  0.   0. ]
 [74.2 75.5  0.   0. ]
 [89.5 89.1  0.   0. ]]

** Qu’est-ce que pd.get_dummies() ?  **  
pandas.get_dummies() transforme une colonne catégorielle (comme une année, un nom de marque, un type…) en une représentation one-hot encoded : c’est-à-dire une matrice binaire où chaque colonne représente une valeur unique de la variable.

In [78]:
df = pd.DataFrame({'Year': [2021, 2022, 2023, 2022]})
print(df)
pd.get_dummies(df['Year'])

   Year
0  2021
1  2022
2  2023
3  2022

   2021  2022  2023
0     1     0     0
1     0     1     0
2     0     0     1
3     0     1     0

Chaque ligne a un seul 1, et tous les autres en 0 → d'où le nom one-hot.

Tu peux même préciser un préfixe ou changer le type des colonnes :

In [77]:
pd.get_dummies(df['Year'], prefix='Year', dtype=float)

   Year_2021  Year_2022  Year_2023
0        1.0        0.0        0.0
1        0.0        1.0        0.0
2        0.0        0.0        1.0
3        0.0        1.0        0.0

## df2matrix_manual : sans boucle ni get_dummies

Ultra-performant (tout en numpy vectorisé ).

Pas de boucle lente.

Plus de contrôle sur l’ordre des années.

Fonctionne même si les années ne sont pas triées dans df.

In [80]:
def df2matrix_manual(df):
    # Étape 1 : extraction des scores
    #  extrait directement les deux colonnes numériques en numpy array.=> un tableau shape (n, 2)
    score_data = df[['MeanScore', 'MedianScore']].to_numpy()

    # Étape 2 : construction one-hot "à la main"
    #  extrait la colonne des années 
    years = df['GradYear'].to_numpy()
    # identifie les années uniques, triées. Pourquoi ?
    # Pour garantir un ordre stable des colonnes dans la matrice one-hot.
    # Le tri est important pour la cohérence.
    unique_years = np.sort(np.unique(years))  # [2021, 2022, 2023]
    
    #On convertit chaque année en indice :
    # 2021 → 0, 2022 → 1, etc.  np.searchsorted est très rapide car unique_years est trié.
    
    year_indices = np.searchsorted(unique_years, years)  # indices de chaque année
    # On crée une matrice binaire pleine de 0, avec :
    # une ligne par étudiant
    # une colonne par année unique
    one_hot = np.zeros((len(years), len(unique_years)))
    # calcul vectorisé ici 
    # np.arange(len(years)) donne les lignes
    # year_indices donne les colonnes où mettre les 1
    # On remplit la matrice en une seule ligne (sans boucle !)
    one_hot[np.arange(len(years)), year_indices] = 1

    # Étape 3 : concaténation finale
    # hstack assemble les colonnes.
    return np.hstack([score_data, one_hot])

my_data=init_data()
print(my_data, '\n')   # Example input
print(df2matrix_manual(my_data))

  FirstName  LastName  GradYear  MeanScore  MedianScore
0      Jack       Doe      2021       90.6         90.0
1       Sam  Williams      2022       88.7         88.5
2      Jenn     Smith      2023       74.2         75.5
3      Beth    Parker      2022       89.5         89.1

[[90.6 90.   1.   0.   0. ]
 [88.7 88.5  0.   1.   0. ]
 [74.2 75.5  0.   0.   1. ]
 [89.5 89.1  0.   1.   0. ]]

# Exercice OneHotEncoder

encodage onehot des variables categorielles seulement : nettoyage des données

![wCool code22](test_mchln/test_bitcoin.png)
![wCool code23](test_mchln/test_bitcoin2.png)
![wCool code24](test_mchln/test_bitcoin3.png)

 transactions    mood restrictions   integrations  media  price
0        243243   crash       banned  noIntegration    0.6   9008
1        578123  stable    Regulated         PayPal    0.7  16065
2        351780    good         free  nointegration    0.8  17076
3         34098     NaN    regulated         yandex    0.9  19341
4         34098  Stable         free         Paypal    0.9   4789

In [89]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
dataframe = pd.read_csv("dataframe.csv", sep=",")
dataframe

   transactions    mood restrictions   integrations  media  price
0        243243   crash       banned  noIntegration    0.6   9008
1        578123  stable    Regulated         PayPal    0.7  16065
2        351780    good         free  nointegration    0.8  17076
3         34098     NaN    regulated         yandex    0.9  19341
4         34098  Stable         free         Paypal    0.9   4789

## preprocess du fichier

In [84]:
def preprocess(dataframe):
    # Your code goes here
    print(dataframe)
    encoder = OneHotEncoder(sparse=False)
    cols=[ 'mood','restrictions','integrations','d']
    #unique_values = list(dataframe['transactions'].unique())
    one_col=['243243','578123','351780','34098','34098']
    #one_col=dataframe['transactions'].reshape(-1)
    print(one_col)
    one_hot_encod = encoder.fit_transform(dataframe[['transactions']])
    print(one_hot_encod)
    #pd.DataFrame(one_hot_encod, columns=dataframe['transactions'])
    df_new = pd.concat([dataframe['media'], pd.DataFrame(one_hot_encod, columns=[cols])], axis=1)
    return df_new

def preprocess1(df):
    # Your code goes here
    # Utilisons la méthode 'get_dummies' de pandas pour effectuer le one-hot encoding
    cols=[ 'mood','restrictions','integrations']
    one_hot_encod = pd.get_dummies(df[cols])
    df_new = pd.concat([df['transactions'], one_hot_encod], axis=1)
    return df_new

In [85]:
mydataframe = pd.read_csv("dataframe.csv", sep=",")
print(preprocess1(mydataframe))

   transactions  mood_Stable  mood_crash  mood_good  mood_stable  \
0        243243            0           1          0            0
1        578123            0           0          0            1
2        351780            0           0          1            0
3         34098            0           0          0            0
4         34098            1           0          0            0

   restrictions_Regulated  restrictions_banned  restrictions_free  \
0                       0                    1                  0
1                       1                    0                  0
2                       0                    0                  1
3                       0                    0                  0
4                       0                    0                  1

   restrictions_regulated  integrations_PayPal  integrations_Paypal  \
0                       0                    0                    0
1                       0                    1                    0
2                       0                    0                    0
3                       1                    0                    0
4                       0                    0                    1

   integrations_noIntegration  integrations_nointegration  integrations_yandex
0                           1                           0                    0
1                           0                           0                    0
2                           0                           1                    0
3                           0                           0                    1
4                           0                           0                    0

In [86]:
mydataframe = pd.read_csv("dataframe.csv", sep=",")
#print(preprocess1(mydataframe))
print(preprocess(mydataframe))

   transactions    mood restrictions   integrations  media  price
0        243243   crash       banned  noIntegration    0.6   9008
1        578123  stable    Regulated         PayPal    0.7  16065
2        351780    good         free  nointegration    0.8  17076
3         34098     NaN    regulated         yandex    0.9  19341
4         34098  Stable         free         Paypal    0.9   4789
['243243', '578123', '351780', '34098', '34098']
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
   media  (mood,)  (restrictions,)  (integrations,)  (d,)
0    0.6      0.0              1.0              0.0   0.0
1    0.7      0.0              0.0              0.0   1.0
2    0.8      0.0              0.0              1.0   0.0
3    0.9      1.0              0.0              0.0   0.0
4    0.9      1.0              0.0              0.0   0.0

C:\Users\jphal\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [93]:
# version getdummies : pas de nettoyage des valeurs => trop de categories

def preprocess(df):
    # Extraire les colonnes mood restrictions   integrations
    selection_data = df[['mood', 'restrictions','integrations']]

    # if isinstance(selection_data, pd.DataFrame):
    mod_data_encoded = pd.get_dummies(selection_data['mood'], dtype=float)
    res_data_encoded = pd.get_dummies(selection_data['restrictions'], dtype=float)
    int_data_encoded = pd.get_dummies(selection_data['integrations'], dtype=float)
    
    # Conversion en numpy array
    mod_data_array = mod_data_encoded.to_numpy()
    res_data_array = res_data_encoded.to_numpy()
    int_data_array = int_data_encoded.to_numpy()

    # Combinaison scores + one-hot GradYear
    final_matrix = np.hstack([mod_data_array, res_data_array,int_data_array])
    return final_matrix
preprocess(dataframe)

array([[0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.]])

In [96]:
# si valeur vide ou nan pour mod => mettre stable
# annuler la casse des strings
import pandas as pd
import numpy as np

def preprocess(df):
    # Sélection des colonnes cibles
    selection_data = df[['mood', 'restrictions', 'integrations']].copy()

    # Nettoyage : minuscules et remplissage des NaN
    for col in selection_data.columns:
        selection_data[col] = selection_data[col].str.lower().fillna('stable')

    # Encodage one-hot de chaque colonne
    mod_data_encoded = pd.get_dummies(selection_data['mood'], prefix='m', dtype=float)
    res_data_encoded = pd.get_dummies(selection_data['restrictions'], prefix='r', dtype=float)
    int_data_encoded = pd.get_dummies(selection_data['integrations'], prefix='i', dtype=float)

    # Combinaison en une seule matrice
    final_matrix = np.hstack([
        mod_data_encoded.to_numpy(),
        res_data_encoded.to_numpy(),
        int_data_encoded.to_numpy()
    ])

    return final_matrix
preprocess(dataframe)

[[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 0. 1. 0.]]

In [110]:
# version df et entete colonne
import pandas as pd
import numpy as np

def preprocess0(df):
    # Extraire les colonnes mood, restrictions, integrations
    selection_data = df[['mood', 'restrictions', 'integrations']]
    for col in selection_data.columns:
        selection_data[col] = selection_data[col].str.lower().fillna('stable')
        #selection_data.loc[:,col] = selection_data[col].astype(str).str.lower().fillna('stable') # tjs warining?

    # Appliquer get_dummies avec préfixes personnalisés
    mod_data_encoded = pd.get_dummies(selection_data['mood'], dtype=float, prefix='m')
    res_data_encoded = pd.get_dummies(selection_data['restrictions'], dtype=float, prefix='r')
    int_data_encoded = pd.get_dummies(selection_data['integrations'], dtype=float, prefix='i')

    # Combinaison des données encodées avec hstack => transforme en numpy
    final_array = np.hstack([mod_data_encoded, res_data_encoded, int_data_encoded])

    # Créer le DataFrame avec les noms de colonnes appropriés
    final_columns = list(mod_data_encoded.columns) + list(res_data_encoded.columns) + list(int_data_encoded.columns)
    final_df = pd.DataFrame(final_array, columns=final_columns)
    
    return final_df

preprocess0(dataframe)

C:\Users\jphal\AppData\Local\Temp\ipykernel_9072\3907966395.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selection_data[col] = selection_data[col].str.lower().fillna('stable')

,m_crash,m_good,m_stable,r_banned,r_free,r_regulated,i_nointegration,i_paypal,i_yandex
0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

## OneHotEncoder de sklearn
### exemple countrties/ cities

In [87]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

countries = ['China', 'USA', 'France', 'Italie', 'France']
cities = ['Beijing', 'New York', 'Paris', 'Rome', 'Marseille']

# Imaginons un DataFrame avec les colonnes 'countries' et 'cities' qui contient des valeurs de type string
df = pd.DataFrame({'countries': countries, 'cities': cities})
print(df)
# Créons l'objet OneHotEncoder
encoder = OneHotEncoder(sparse=False)

# Utilisons la méthode 'fit_transform' pour effectuer le one-hot encoding
one_hot_encod = encoder.fit_transform(df[['countries']])
print(one_hot_encod)
# Concaténons la colonne 'cities' avec les données 'countries' encodées en one-hot
df_new = pd.concat([df['cities'], pd.DataFrame(one_hot_encod, columns=['China', 'France', 'Italie', 'USA'])], axis=1)

# Affichons le résultat
df_new

  countries     cities
0     China    Beijing
1       USA   New York
2    France      Paris
3    Italie       Rome
4    France  Marseille
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]

C:\Users\jphal\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

      cities  China  France  Italie  USA
0    Beijing    1.0     0.0     0.0  0.0
1   New York    0.0     0.0     0.0  1.0
2      Paris    0.0     1.0     0.0  0.0
3       Rome    0.0     0.0     1.0  0.0
4  Marseille    0.0     1.0     0.0  0.0

In [88]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

countries = ['China', 'USA', 'France', 'Italie', 'France']
cities = ['Beijing', 'New York', 'Paris', 'Rome', 'Marseille']

# Imaginons un DataFrame avec les colonnes 'countries' et 'cities' qui contient des valeurs de type string
df = pd.DataFrame({'countries': countries, 'cities': cities})
print(df)
# Créons l'objet OneHotEncoder
encoder = OneHotEncoder(sparse=False)

# Utilisons la méthode 'fit_transform' pour effectuer le one-hot encoding
one_hot_encod = encoder.fit_transform(df[['countries']])

# Concaténons la colonne 'cities' avec les données 'countries' encodées en one-hot
df_new = pd.concat([df['cities'], pd.DataFrame(one_hot_encod, columns=['China', 'France', 'Italie', 'USA'])], axis=1)

# Affichons le résultat
df_new

  countries     cities
0     China    Beijing
1       USA   New York
2    France      Paris
3    Italie       Rome
4    France  Marseille

C:\Users\jphal\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

      cities  China  France  Italie  USA
0    Beijing    1.0     0.0     0.0  0.0
1   New York    0.0     0.0     0.0  1.0
2      Paris    0.0     1.0     0.0  0.0
3       Rome    0.0     0.0     1.0  0.0
4  Marseille    0.0     1.0     0.0  0.0

## version Preprocess avec sklearn

Extraire les colonnes pertinentes : Nous sélectionnons uniquement les colonnes mood, restrictions et integrations.

Initialisation de OneHotEncoder :

Le paramètre drop='first' permet de supprimer la première colonne de chaque catégorie, ce qui évite la colinéarité (c'est-à-dire, éviter que la somme des colonnes ne soit égale à 1, ce qui est souvent une bonne pratique pour les modèles statistiques).

Le paramètre sparse=False permet de retourner un tableau numpy plutôt qu'une matrice creuse (spare matrix), ce qui est plus facile à manipuler dans ce cas.

Encodage : Le OneHotEncoder est appliqué sur les colonnes catégorielles mood, restrictions, et integrations. Cela transforme chaque catégorie en une colonne binaire où la valeur est 1 si la catégorie est présente et 0 sinon.

Création du DataFrame final : Nous créons un DataFrame avec les résultats de l'encodage et générons des noms de colonnes en utilisant get_feature_names_out(), ce qui nous donne des noms comme mood_crash, restrictions_banned, etc.

Retour : La fonction retourne le DataFrame encodé.

In [118]:
# version avec sklearn.preprocessing import OneHotEncoder
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

def preprocessX(df):
    # Extraire les colonnes mood, restrictions, et integrations
    selection_data = df[['mood', 'restrictions', 'integrations']]

    # Initialiser l'encodeur OneHotEncoder
    encoder = OneHotEncoder(drop='first', sparse_output=False)

    # Encoder les colonnes catégorielles
    encoded_data = encoder.fit_transform(selection_data)

    # Créer un DataFrame avec les résultats de l'encodage et les noms des colonnes
    encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(selection_data.columns))

    # Retourner le DataFrame encodé
    return encoded_df

preprocessX(dataframe)

,mood_good,mood_stable,restrictions_free,restrictions_regulated,integrations_paypal,integrations_yandex
0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,1.0,1.0,0.0
2,1.0,0.0,1.0,0.0,0.0,0.0
3,0.0,1.0,0.0,1.0,0.0,1.0
4,0.0,1.0,1.0,0.0,1.0,0.0

In [120]:
# Exemple d'appel à la fonction avec autre data
data = pd.DataFrame({
    'mood': ['crash', 'stable', 'good', None, 'Stable'],
    'restrictions': ['banned', 'Regulated', 'free', 'regulated', 'free'],
    'integrations': ['noIntegration', 'PayPal', 'nointegration', 'yandex', 'Paypal'],
    'media': [0.6, 0.7, 0.8, 0.9, 0.9],
    'price': [9008, 16065, 17076, 19341, 4789]
})

processed_data = preprocessX(data)
print(processed_data)

   mood_crash  mood_good  mood_stable  mood_None  restrictions_banned  \
0         1.0        0.0          0.0        0.0                  1.0
1         0.0        0.0          1.0        0.0                  0.0
2         0.0        1.0          0.0        0.0                  0.0
3         0.0        0.0          0.0        1.0                  0.0
4         0.0        0.0          0.0        0.0                  0.0

   restrictions_free  restrictions_regulated  integrations_Paypal  \
0                0.0                     0.0                  0.0
1                0.0                     0.0                  0.0
2                1.0                     0.0                  0.0
3                0.0                     1.0                  0.0
4                1.0                     0.0                  1.0

   integrations_noIntegration  integrations_nointegration  integrations_yandex
0                         1.0                         0.0                  0.0
1                         0.0                         0.0                  0.0
2                         0.0                         1.0                  0.0
3                         0.0                         0.0                  1.0
4                         0.0                         0.0                  0.0